"use strict";

// ============================================================
// 案件データ / 理不尽イベントデータ
// 実在の案件を参考にしたフィクションです。実名は使用していません。
// 毎ゲーム、この中からランダムに5案件が出題されます。
// ============================================================

const CASES = [
  {
    client: "つばさ光テレビ",
    industry: "通信キャリア（光回線+TVバンドル）",
    kpi: "申込CPA 25,000円以内",
    budget: "月300万円",
    absurdity: "中",
    brief:
      "光回線とTVサービスのセット申込を増やしたい。本部からは『若年層にも刺さる施策を』、現場からは『結局申し込むのは50代』という声。どちらも正しい。",
    plans: [
      {
        name: "Google検索・回線乗換ワード",
        horse: "ヒカリケンサクオウ",
        odds: 2.4,
        media: "Google",
        setup: "乗換/工事費ワード / 申込CV / 指名防衛",
        allocation: "検索70%・指名20%・検証10%",
        stats: { fit: 85, stability: 81, burst: 48, client: 64 },
      },
      {
        name: "YDA・比較検討層リターゲ",
        horse: "ヤフーオイコミ",
        odds: 4.8,
        media: "YDA",
        setup: "比較サイト閲覧層 / リタゲ厚め / 静止画",
        allocation: "リタゲ55%・類似30%・検証15%",
        stats: { fit: 72, stability: 66, burst: 62, client: 58 },
      },
      {
        name: "YouTube・工事レポ動画",
        horse: "ドウガコウジチュウ",
        odds: 7.5,
        media: "YouTube",
        setup: "開通までの流れ動画 / 認知〜検討 / CPV重視",
        allocation: "動画75%・検索追撃25%",
        stats: { fit: 60, stability: 58, burst: 70, client: 68 },
      },
      {
        name: "TVer・コネクテッドTV配信",
        horse: "チャノマセンリョウ",
        odds: 13.0,
        media: "TVer",
        setup: "CTV面 / 世帯リーチ / テレビ画面で完結訴求",
        allocation: "CTV85%・計測検証15%",
        stats: { fit: 50, stability: 44, burst: 88, client: 74 },
      },
    ],
    incidents: [
      {
        type: "本部横やり",
        title: "『若年層比率をKPIに追加で』",
        body: "申込は取れているのに、急に年齢構成の説明資料が必要になる。",
        effect: { client: 14, fit: -8 },
      },
      {
        type: "計測事故",
        title: "申込フォーム改修でCVタグが外れる",
        body: "改修担当は悪くない。連絡が来なかっただけ。学習が迷子になる。",
        effect: { stability: -14, fit: -5 },
      },
      {
        type: "奇跡",
        title: "引っ越しシーズンが前倒しで到来",
        body: "回線需要が自然増。刈り取り系が静かに伸びる。",
        effect: { fit: 9, stability: 6 },
      },
    ],
  },
  {
    client: "オンライン専用プラン ぽけっとS",
    industry: "通信（オンライン専用格安プラン）",
    kpi: "新規回線 月1,500件",
    budget: "月200万円",
    absurdity: "高",
    brief:
      "店舗もサポートも削ったオンライン専用プラン。『SNSでバズらせて獲得もしたい』という欲張り要件。バズと獲得は基本的に別の生き物である。",
    plans: [
      {
        name: "X・トレンド連動ポスト広告",
        horse: "トレンドイッキ",
        odds: 3.4,
        media: "X",
        setup: "トレンド便乗 / 自虐系コピー / 拡散狙い",
        allocation: "ポスト広告70%・反応追撃30%",
        stats: { fit: 68, stability: 52, burst: 86, client: 72 },
      },
      {
        name: "Google検索・料金比較ワード",
        horse: "シメイガリホンメイ",
        odds: 2.6,
        media: "Google",
        setup: "料金比較/乗換 / 申込CV / 除外徹底",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 84, stability: 80, burst: 46, client: 56 },
      },
      {
        name: "LINE・友だち追加からナーチャリング",
        horse: "ミドリノコウテイ",
        odds: 5.5,
        media: "LINE",
        setup: "友だち追加 / 配信で教育 / 乗換ハードル低減",
        allocation: "友だち追加60%・配信30%・検証10%",
        stats: { fit: 70, stability: 68, burst: 54, client: 60 },
      },
      {
        name: "TikTok・料金プラン解説ショート",
        horse: "ジーゼットダッシュ",
        odds: 9.8,
        media: "TikTok",
        setup: "早口解説 / コメント欄が本体 / 若年層直撃",
        allocation: "ショート90%・予備10%",
        stats: { fit: 52, stability: 40, burst: 94, client: 62 },
      },
    ],
    incidents: [
      {
        type: "炎上未遂",
        title: "自虐コピーが一部で燃えかける",
        body: "拡散はした。ポジティブとは言っていない。広報が会議を招集。",
        effect: { burst: -12, client: -8, stability: -4 },
      },
      {
        type: "競合動向",
        title: "競合が同日に値下げを発表",
        body: "比較表が一晩で古くなる。検索ワードの意図が変わる。",
        effect: { fit: -9, stability: -6 },
      },
      {
        type: "奇跡",
        title: "解説ショートがなぜか跳ねる",
        body: "投稿3本目にして急にアルゴリズムに愛される。SNS勢が加速。",
        effect: { burst: 15, client: 7 },
      },
    ],
  },
  {
    client: "スポーツ配信 スポマックスLIVE",
    industry: "動画配信サービス（スポーツ）",
    kpi: "無料トライアル登録CPA 4,000円以内",
    budget: "月500万円",
    absurdity: "中",
    brief:
      "開幕戦に向けて無料トライアルを最大化したい。ただし『解約前提のユーザーはいらない』という難しい注文つき。試合日程で需要が乱高下する。",
    plans: [
      {
        name: "Meta・名場面リール配信",
        horse: "メタメイバメン",
        odds: 3.2,
        media: "Facebook/Instagram",
        setup: "ハイライト風リール / 広め配信 / 登録LP直送",
        allocation: "リール65%・静止画20%・リタゲ15%",
        stats: { fit: 78, stability: 64, burst: 74, client: 58 },
      },
      {
        name: "Google検索・観戦方法ワード",
        horse: "カンセンケンサク",
        odds: 2.9,
        media: "Google",
        setup: "『試合 視聴方法』ワード / 需要刈り取り",
        allocation: "検索80%・指名10%・検証10%",
        stats: { fit: 84, stability: 76, burst: 50, client: 54 },
      },
      {
        name: "ABEMA Ads・スポーツ好き面",
        horse: "レンダンアベマ",
        odds: 8.6,
        media: "ABEMA Ads",
        setup: "スポーツコンテンツ隣接面 / 動画15秒",
        allocation: "動画80%・検証20%",
        stats: { fit: 62, stability: 56, burst: 72, client: 66 },
      },
      {
        name: "The Trade Desk・CTV一点勝負",
        horse: "リビングジャック",
        odds: 14.5,
        media: "The Trade Desk",
        setup: "CTV / 世帯ターゲティング / 大画面で臨場感",
        allocation: "CTV90%・計測10%",
        stats: { fit: 48, stability: 42, burst: 90, client: 76 },
      },
    ],
    incidents: [
      {
        type: "配信事故",
        title: "注目カードが雨天中止",
        body: "需要予測が崩壊。検索ボリュームが蒸発する。",
        effect: { fit: -10, burst: -8 },
      },
      {
        type: "権利カットイン",
        title: "名場面素材の使用範囲に指摘",
        body: "一番強いクリエイティブが差し替えに。リーガルは正しい。つらいだけ。",
        effect: { burst: -14, stability: 4 },
      },
      {
        type: "奇跡",
        title: "無名の若手選手が大活躍",
        body: "SNSがお祭りに。ハイライト系クリエイティブが火を吹く。",
        effect: { burst: 16, fit: 6 },
      },
    ],
  },
  {
    client: "駅前英会話 ブライト",
    industry: "英会話スクール",
    kpi: "無料体験予約 月60件",
    budget: "月90万円",
    absurdity: "中",
    brief:
      "4月の入会シーズンに向けて無料体験を集めたい。校長は『英語で人生が広がる』系の情緒訴求が好きだが、予約が取れるのはいつも料金訴求である。",
    plans: [
      {
        name: "Google検索・地域×英会話",
        horse: "エキマエホンメイ",
        odds: 2.5,
        media: "Google",
        setup: "地域名×英会話 / 体験予約CV / 電話併用",
        allocation: "検索75%・マップ15%・検証10%",
        stats: { fit: 86, stability: 80, burst: 44, client: 58 },
      },
      {
        name: "Meta・リード広告で体験予約",
        horse: "リードスグトレル",
        odds: 4.3,
        media: "Facebook/Instagram",
        setup: "フォーム一体型 / 学習意欲層 / 入力3項目",
        allocation: "リード広告70%・リタゲ20%・検証10%",
        stats: { fit: 74, stability: 62, burst: 66, client: 54 },
      },
      {
        name: "SmartNews・学び直し記事面",
        horse: "スマニューシブトイ",
        odds: 8.0,
        media: "SmartNews",
        setup: "記事風クリエイティブ / 30-50代 / 朝夕配信",
        allocation: "記事面80%・検証20%",
        stats: { fit: 58, stability: 60, burst: 62, client: 62 },
      },
      {
        name: "Taboola・体験談ネイティブ枠",
        horse: "タイケンダンナガレ",
        odds: 15.5,
        media: "Taboola",
        setup: "体験談記事LP / ネイティブ面 / 低CPC大量流入",
        allocation: "ネイティブ85%・LP改善15%",
        stats: { fit: 46, stability: 40, burst: 88, client: 50 },
      },
    ],
    incidents: [
      {
        type: "校長カットイン",
        title: "『人生が広がる』コピーを強制採用",
        body: "情緒は満たされた。クリック率は静かになった。",
        effect: { client: 15, fit: -7 },
      },
      {
        type: "現場事故",
        title: "体験枠が講師のシフト都合で半減",
        body: "広告は好調なのに予約枠がない。機会損失が数字に出る。",
        effect: { stability: -12, burst: -6 },
      },
      {
        type: "市況",
        title: "大手が春の入会金無料を開始",
        body: "比較される。料金と導線が明確なプランだけ耐える。",
        effect: { fit: -7, stability: -5, client: -4 },
      },
    ],
  },
  {
    client: "まもりあ生命 ネット保険",
    industry: "生命保険（通信系バンドル）",
    kpi: "資料請求CPA 12,000円以内",
    budget: "月150万円",
    absurdity: "高",
    brief:
      "通信契約とセットの割引が売りのネット生保。金融広告なので審査は厳しく、表現の自由度は低い。それでいて『もっとエモく』という要望が来ている。",
    plans: [
      {
        name: "Yahoo!検索・保険見直しワード",
        horse: "ミナオシケンサク",
        odds: 2.8,
        media: "Yahoo!",
        setup: "見直し/比較ワード / 資料請求CV / 40-60代",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 84, stability: 78, burst: 46, client: 60 },
      },
      {
        name: "GDN・ライフイベント配信",
        horse: "ジーディーエヌコツコツ",
        odds: 4.6,
        media: "GDN",
        setup: "結婚/出産インテント / 静止画 / CPC抑制",
        allocation: "インテント60%・リタゲ25%・検証15%",
        stats: { fit: 72, stability: 70, burst: 52, client: 56 },
      },
      {
        name: "LINE・家計相談トーク導線",
        horse: "カケイボトーク",
        odds: 6.2,
        media: "LINE",
        setup: "友だち追加→家計診断 / ナーチャリング",
        allocation: "友だち追加55%・配信30%・検証15%",
        stats: { fit: 64, stability: 62, burst: 58, client: 66 },
      },
      {
        name: "Outbrain・読み物LP勝負",
        horse: "ヨミモノギャンブル",
        odds: 17.0,
        media: "Outbrain",
        setup: "保険コラムLP / ネイティブ面 / 情緒訴求全開",
        allocation: "ネイティブ85%・LP検証15%",
        stats: { fit: 44, stability: 38, burst: 90, client: 70 },
      },
    ],
    incidents: [
      {
        type: "審査カットイン",
        title: "『安心』の根拠提示を求められる",
        body: "金融広告の審査は正確である。締切には冷たいが。",
        effect: { stability: -16, burst: -6 },
      },
      {
        type: "クライアント横やり",
        title: "『もっとエモい動画に差し替えて』",
        body: "エモさは審査を通らない。通る範囲のエモさが爆誕する。",
        effect: { client: 14, stability: -8 },
      },
      {
        type: "奇跡",
        title: "家計見直し特集がテレビで放送",
        body: "『保険 見直し』の検索が急増。刈り取り系が潤う。",
        effect: { fit: 10, stability: 5 },
      },
    ],
  },
  {
    client: "あおぞら県 観光誘客キャンペーン",
    industry: "自治体・官公庁",
    kpi: "特設サイト訪問 30万セッション",
    budget: "期間3ヶ月で400万円",
    absurdity: "極",
    brief:
      "県の観光キャンペーン。KPIはセッション数だが、本当のKPIは『議会で説明できること』。ブランドセーフティ要件が民間案件の3倍厳しい。",
    plans: [
      {
        name: "YouTube・観光PR動画",
        horse: "ケンチョウドウガ",
        odds: 3.0,
        media: "YouTube",
        setup: "絶景ドローン動画 / 認知拡大 / 面の説明が容易",
        allocation: "動画80%・検索追撃20%",
        stats: { fit: 78, stability: 76, burst: 56, client: 74 },
      },
      {
        name: "DV360・PMPで面を完全指定",
        horse: "ピーエムピーカタメ",
        odds: 4.4,
        media: "DV360",
        setup: "PMP取引 / ホワイトリスト面のみ / 議会対応万全",
        allocation: "PMP85%・レポート整備15%",
        stats: { fit: 70, stability: 82, burst: 42, client: 80 },
      },
      {
        name: "X・ご当地バズ企画",
        horse: "バズラセタガリ",
        odds: 6.8,
        media: "X",
        setup: "ご当地ネタ / ハッシュタグ企画 / 拡散狙い",
        allocation: "ポスト広告70%・企画30%",
        stats: { fit: 58, stability: 46, burst: 88, client: 52 },
      },
      {
        name: "Teads・上品なインリード動画",
        horse: "ジョウヒンインリード",
        odds: 10.5,
        media: "Teads",
        setup: "プレミア媒体面 / インリード動画 / 品位重視",
        allocation: "インリード80%・検証20%",
        stats: { fit: 52, stability: 64, burst: 60, client: 78 },
      },
    ],
    incidents: [
      {
        type: "議会カットイン",
        title: "『この広告費の妥当性は』と質問が出る",
        body: "資料作成に運用者の魂が3日吸われる。入札調整が止まる。",
        effect: { stability: -10, client: 8 },
      },
      {
        type: "ブランドセーフティ",
        title: "配信面リストの再提出を求められる",
        body: "面が絞られる。安全だが、リーチも安全な数字になる。",
        effect: { burst: -12, client: 10 },
      },
      {
        type: "奇跡",
        title: "県の名物がドラマの舞台に",
        body: "誰も予算を使っていないのに検索が伸びる。行政の勝利。",
        effect: { fit: 12, burst: 8 },
      },
    ],
  },
  {
    client: "新作RPG グリモワール学園",
    industry: "ゲーム（コンシューマ新作）",
    kpi: "発売週DL数 + 予約数",
    budget: "発売前後6週で800万円",
    absurdity: "高",
    brief:
      "魔法学園が舞台の大型新作RPG。ファンの熱量は高いが、ネタバレと炎上のリスクも高い。海外本社からは『グローバル統一クリエイティブで』という無茶が届いている。",
    plans: [
      {
        name: "YouTube・トレーラー指名配信",
        horse: "トレーラーホンメイ",
        odds: 2.7,
        media: "YouTube",
        setup: "公式トレーラー / ゲーム実況隣接面 / 予約CV",
        allocation: "動画70%・検索指名20%・検証10%",
        stats: { fit: 84, stability: 74, burst: 58, client: 62 },
      },
      {
        name: "TikTok・プレイ切り抜き",
        horse: "キリヌキマホウ",
        odds: 4.5,
        media: "TikTok",
        setup: "15秒プレイ映像 / 音ハメ編集 / 拡散狙い",
        allocation: "ショート80%・反応追撃20%",
        stats: { fit: 68, stability: 50, burst: 92, client: 56 },
      },
      {
        name: "X・ファンアート文脈参入",
        horse: "コスプレバズ",
        odds: 7.2,
        media: "X",
        setup: "ファンコミュニティ文脈 / UGC活性化",
        allocation: "ポスト広告65%・企画35%",
        stats: { fit: 60, stability: 48, burst: 84, client: 58 },
      },
      {
        name: "ASA・ストア検索一点突破",
        horse: "ストアイッテン",
        odds: 12.0,
        media: "ASA",
        setup: "App Store検索 / 関連タイトル指名 / DL直結",
        allocation: "ASA90%・キーワード検証10%",
        stats: { fit: 54, stability: 66, burst: 52, client: 48 },
      },
    ],
    incidents: [
      {
        type: "本社カットイン",
        title: "グローバル統一バナーの使用を指示",
        body: "日本のファンに刺さらない色使い。ローカライズの意味を全員が考える。",
        effect: { client: 12, fit: -10 },
      },
      {
        type: "ネタバレ事故",
        title: "海外で発売が1日早く、実況が解禁",
        body: "重大ネタバレがトレンド入り。認知は上がった。複雑な気持ちで。",
        effect: { burst: 10, client: -8, stability: -6 },
      },
      {
        type: "奇跡",
        title: "有名実況者が自腹で48時間配信",
        body: "依頼していない。愛だけがそこにある。UGC系が大加速。",
        effect: { burst: 16, fit: 7 },
      },
    ],
  },
  {
    client: "ふんわりプレミア柔軟剤",
    industry: "日用品メーカー（新商品）",
    kpi: "EC売上 + 店頭想起",
    budget: "発売月450万円",
    absurdity: "中",
    brief:
      "香りが12時間続く新作柔軟剤。ECでの売上と店頭での想起を同時に求められている。宣伝部は『デジタルでテレビ並みのリーチを』と言う。予算はテレビの10分の1である。",
    plans: [
      {
        name: "Amazon Ads・カテゴリ刈り取り",
        horse: "カゴオチシラズ",
        odds: 2.6,
        media: "Amazon",
        setup: "柔軟剤カテゴリ / スポンサープロダクト / 購入直結",
        allocation: "SP70%・ブランド枠20%・検証10%",
        stats: { fit: 86, stability: 80, burst: 44, client: 54 },
      },
      {
        name: "Meta・香り体験リール",
        horse: "カオリバズーカ",
        odds: 4.2,
        media: "Facebook/Instagram",
        setup: "香り擬人化リール / 主婦層 / EC送客",
        allocation: "リール65%・静止画20%・リタゲ15%",
        stats: { fit: 72, stability: 60, burst: 78, client: 64 },
      },
      {
        name: "Gunosy・比較記事ネイティブ",
        horse: "キジメンジミー",
        odds: 9.4,
        media: "Gunosy",
        setup: "柔軟剤比較記事 / ネイティブ面 / 低CPC",
        allocation: "記事面80%・LP改善20%",
        stats: { fit: 54, stability: 58, burst: 60, client: 52 },
      },
      {
        name: "ChatGPT広告・新チャネル人柱",
        horse: "エーアイサキガケ",
        odds: 23.0,
        media: "ChatGPT",
        setup: "会話文脈ターゲティング / 誰も正解を知らない",
        allocation: "新枠90%・祈り10%",
        stats: { fit: 42, stability: 34, burst: 96, client: 72 },
      },
    ],
    incidents: [
      {
        type: "宣伝部横やり",
        title: "『とにかくリーチの数字を大きく』",
        body: "獲得系の予算が認知系へ移動。ECの数字が静かになる。",
        effect: { client: 12, fit: -9 },
      },
      {
        type: "供給事故",
        title: "EC在庫が想定より早く欠品",
        body: "広告は絶好調。買えないだけ。機会損失レポートが生まれる。",
        effect: { burst: -14, stability: -6 },
      },
      {
        type: "奇跡",
        title: "香りマニアの投稿がバズる",
        body: "『12時間持続は本当か検証してみた』が拡散。指名検索が急増。",
        effect: { burst: 12, fit: 8 },
      },
    ],
  },
];

// どの案件でも起こりうる汎用ハプニング。毎レースここから抽選で混ざるため展開が毎回変わる。
const GENERIC_INCIDENTS = [
  {
    type: "計測事故",
    title: "GTMのタグが誰かの『検証』で止まっていた",
    body: "コンバージョンが3時間分消失。学習がリセット気味に。",
    effect: { fit: -6, stability: -9 },
  },
  {
    type: "媒体アップデート",
    title: "入札アルゴリズムがサイレント変更",
    body: "リリースノートには何も書いていない。挙動だけが変わる。",
    effect: { stability: -10, burst: 7 },
  },
  {
    type: "奇跡",
    title: "競合が予算を使い切って撤退",
    body: "オークションが突然ぬるくなる。CPCが静かに下がる。",
    effect: { fit: 7, burst: 8 },
  },
  {
    type: "クライアント横やり",
    title: "『バナーは全部赤にして』",
    body: "赤くなった。CTRは上がったのか下がったのか誰にも分からない。",
    effect: { client: 13, fit: -6 },
  },
  {
    type: "予算事故",
    title: "請求上限に到達して配信が夕方に停止",
    body: "カードの上限申請は明日以降。ゴールデンタイムが沈黙する。",
    effect: { burst: -12, stability: -5 },
  },
  {
    type: "代理店あるある",
    title: "レポート提出日とレース日が重なる",
    body: "運用者の集中力が資料作成に吸われる。微調整が止まる。",
    effect: { stability: -6, client: 6 },
  },
  {
    type: "奇跡",
    title: "インフルエンサーが勝手に紹介してくれた",
    body: "誰も依頼していない。指名検索とSNS流入が同時に伸びる。",
    effect: { burst: 12, client: 6 },
  },
];
