"use strict";

// ============================================================
// 案件データ / 理不尽イベントデータ
// ============================================================

const CASES = [
  {
    client: "白金スキンラボ",
    industry: "美容クリニック",
    kpi: "予約CPA 18,000円以内",
    budget: "月80万円",
    absurdity: "高",
    brief:
      "高級感を崩さず、今月だけ予約数を2倍にしたい。院長は強い訴求が好きだが、薬機法とブランド毀損は絶対NG。",
    plans: [
      {
        name: "検索広告・症状名完全一致",
        horse: "ケンサクホンメイ",
        odds: 2.6,
        media: "Google",
        setup: "完全一致中心 / CV最大化 / LPは既存",
        allocation: "検索70%・リマケ20%・検証10%",
        stats: { fit: 86, stability: 82, burst: 48, client: 62 },
      },
      {
        name: "Meta・美容悩み動画訴求",
        horse: "メタビヨウバズ",
        odds: 4.4,
        media: "Meta",
        setup: "広め配信 / 動画3本 / 予約LP直送",
        allocation: "動画60%・静止画25%・リマケ15%",
        stats: { fit: 74, stability: 58, burst: 82, client: 54 },
      },
      {
        name: "YouTube・院長ブランディング",
        horse: "インチョウニンチ",
        odds: 8.8,
        media: "YouTube",
        setup: "認知寄せ / CPV重視 / 指名検索狙い",
        allocation: "動画80%・検索追撃20%",
        stats: { fit: 54, stability: 64, burst: 42, client: 76 },
      },
      {
        name: "TikTok・症例風UGC",
        horse: "ショウレイダッシュ",
        odds: 14.2,
        media: "TikTok",
        setup: "UGC風 / 若年層広め / 勢い重視",
        allocation: "UGC90%・予備10%",
        stats: { fit: 46, stability: 38, burst: 94, client: 35 },
      },
    ],
    incidents: [
      {
        type: "法務カットイン",
        title: "一番強いコピーが差し戻し",
        body: "『たるみ改善』がNG判定。強かった訴求ほど失速。",
        effect: { burst: -16, fit: -8, stability: 3 },
      },
      {
        type: "クライアント横やり",
        title: "院長が急に高級路線へ回帰",
        body: "派手なクリエイティブが全停止。上品な面構えだけが残る。",
        effect: { client: 18, burst: -10 },
      },
      {
        type: "媒体事故",
        title: "審査落ち理由が不明",
        body: "問い合わせてもテンプレ回答。配信再開まで半日ロス。",
        effect: { stability: -14 },
      },
    ],
  },
  {
    client: "クラウド勤怠SaaS",
    industry: "BtoB SaaS",
    kpi: "商談化リード30件",
    budget: "月120万円",
    absurdity: "中",
    brief:
      "リード数を3倍にしたいが、情報収集層は不要。役員からは『競合より知的に見せて』という曖昧な要望も来ている。",
    plans: [
      {
        name: "検索広告・課題顕在ワード",
        horse: "ケンサクショウダン",
        odds: 2.2,
        media: "Google",
        setup: "勤怠管理 / 比較 / 資料請求CV",
        allocation: "検索75%・リマケ15%・除外調整10%",
        stats: { fit: 88, stability: 84, burst: 44, client: 70 },
      },
      {
        name: "LinkedIn・職種ターゲット",
        horse: "リンクドインリッチ",
        odds: 6.5,
        media: "LinkedIn",
        setup: "人事責任者 / ホワイトペーパー",
        allocation: "役職配信85%・検証15%",
        stats: { fit: 82, stability: 61, burst: 40, client: 82 },
      },
      {
        name: "Meta・診断LPで刈り取り",
        horse: "メタシンダン",
        odds: 7.1,
        media: "Meta",
        setup: "類似拡張 / 診断コンテンツ / MA連携",
        allocation: "類似60%・興味25%・リマケ15%",
        stats: { fit: 63, stability: 55, burst: 72, client: 48 },
      },
      {
        name: "Display・競合面リマーケ",
        horse: "バナーオイコミ",
        odds: 11.4,
        media: "GDN",
        setup: "競合関連面 / リマケ強め / CPC抑制",
        allocation: "競合面50%・リマケ40%・検証10%",
        stats: { fit: 50, stability: 50, burst: 58, client: 41 },
      },
    ],
    incidents: [
      {
        type: "営業カットイン",
        title: "リードの質に営業が首をひねる",
        body: "件数は出たが『温度感が低い』判定。商談化補正が入る。",
        effect: { fit: -10, client: -12, stability: 5 },
      },
      {
        type: "役員レビュー",
        title: "急にブランドトーンが上品になる",
        body: "勝ちコピーが『軽い』と言われ、資料請求CTAが弱まる。",
        effect: { client: 14, burst: -12 },
      },
      {
        type: "奇跡",
        title: "比較記事が検索上位に浮上",
        body: "指名検索がじわっと伸び、検索系が後半に粘る。",
        effect: { fit: 8, stability: 8 },
      },
    ],
  },
  {
    client: "駅前もつ焼き だるま",
    industry: "飲食店",
    kpi: "週末予約40件",
    budget: "7日で12万円",
    absurdity: "高",
    brief:
      "今週末だけ席を埋めたい。店長は『地元感』を出したいが、写真素材は暗い店内写真が3枚だけ。",
    plans: [
      {
        name: "Googleマップ広告・近隣狙い",
        horse: "マップチカミチ",
        odds: 3.1,
        media: "Google",
        setup: "半径3km / 電話CV / 来店意図強め",
        allocation: "マップ65%・検索25%・電話10%",
        stats: { fit: 82, stability: 72, burst: 56, client: 66 },
      },
      {
        name: "Instagram・地元飯リール",
        horse: "ジモトメシリール",
        odds: 4.9,
        media: "Instagram",
        setup: "近隣20-40代 / リール / DM予約",
        allocation: "リール70%・ストーリーズ20%・DM10%",
        stats: { fit: 70, stability: 52, burst: 86, client: 70 },
      },
      {
        name: "X・本日空席ポスト広告",
        horse: "クウセキソクホウ",
        odds: 9.6,
        media: "X",
        setup: "地域ワード / 当日訴求 / 低予算高速",
        allocation: "当日投稿80%・反応追撃20%",
        stats: { fit: 56, stability: 42, burst: 72, client: 46 },
      },
      {
        name: "TikTok・店長出演ショート",
        horse: "テンチョウバクチ",
        odds: 18.0,
        media: "TikTok",
        setup: "顔出し / おすすめ料理 / ノリ重視",
        allocation: "店長動画100%",
        stats: { fit: 42, stability: 34, burst: 98, client: 58 },
      },
    ],
    incidents: [
      {
        type: "現場カットイン",
        title: "店長が撮影日に仕込みで不在",
        body: "動画素材が撮れず、静止画と根性で勝負することに。",
        effect: { burst: -18, stability: 4 },
      },
      {
        type: "天候事故",
        title: "週末に大雨予報",
        body: "来店意欲が鈍る。近場需要と予約導線だけが粘る。",
        effect: { fit: -6, stability: -8, client: -4 },
      },
      {
        type: "奇跡",
        title: "常連の投稿がなぜか伸びる",
        body: "地元ユーザーのコメント欄が温まり、SNS勢が加速。",
        effect: { burst: 16, client: 8 },
      },
    ],
  },
  {
    client: "人生逆転オンライン講座",
    industry: "教育・情報商材寄り",
    kpi: "説明会CPA 9,800円以内",
    budget: "月60万円",
    absurdity: "極",
    brief:
      "強い言葉で売りたいが、審査落ちは避けたい。代表は『人生が変わる』と言いたい。媒体はたぶん嫌がっている。",
    plans: [
      {
        name: "Meta・安全寄せ無料診断",
        horse: "アンゼンメタ",
        odds: 3.8,
        media: "Meta",
        setup: "無料診断 / 表現丸め / LPで教育",
        allocation: "安全訴求70%・リマケ20%・検証10%",
        stats: { fit: 76, stability: 68, burst: 54, client: 50 },
      },
      {
        name: "検索広告・悩みワード一点突破",
        horse: "ナヤミケンサク",
        odds: 4.1,
        media: "Google",
        setup: "悩み顕在 / 説明会CV / 除外強め",
        allocation: "検索80%・指名10%・除外調整10%",
        stats: { fit: 78, stability: 70, burst: 45, client: 58 },
      },
      {
        name: "YouTube・長尺ストーリー広告",
        horse: "ストーリーナガシ",
        odds: 8.5,
        media: "YouTube",
        setup: "体験談風 / 視聴維持 / 認知から刈る",
        allocation: "長尺75%・リマケ25%",
        stats: { fit: 60, stability: 56, burst: 74, client: 72 },
      },
      {
        name: "TikTok・煽り切り抜き",
        horse: "アオリバズーカ",
        odds: 21.0,
        media: "TikTok",
        setup: "強め冒頭 / 代表語録 / 爆発狙い",
        allocation: "煽り動画90%・祈り10%",
        stats: { fit: 48, stability: 28, burst: 100, client: 78 },
      },
    ],
    incidents: [
      {
        type: "審査カットイン",
        title: "『誰でも変われる』が刺される",
        body: "断定表現がNG。勢いで勝っていたプランほど急停止。",
        effect: { stability: -20, burst: -8 },
      },
      {
        type: "代表横やり",
        title: "代表がLPに赤字見出しを追加",
        body: "CVRは少し上がるが、媒体の空気が明らかに冷える。",
        effect: { burst: 10, stability: -14, client: 8 },
      },
      {
        type: "計測事故",
        title: "サンクスページCVが二重発火",
        body: "一瞬だけ勝って見える。現実は管理画面の外にある。",
        effect: { fit: -4, client: -10 },
      },
    ],
  },
  {
    client: "地方製造業 採用PJ",
    industry: "採用広告",
    kpi: "応募15件",
    budget: "月35万円",
    absurdity: "中",
    brief:
      "若手を採用したいが、勤務地は駅から遠い。社長は『家族みたいな職場』を推したいが、求職者はたぶんそこを見ていない。",
    plans: [
      {
        name: "Indeed・職種検索刈り取り",
        horse: "インディードコツコツ",
        odds: 2.9,
        media: "Indeed",
        setup: "職種軸 / 給与明記 / 応募導線短縮",
        allocation: "職種検索80%・原稿改善20%",
        stats: { fit: 84, stability: 78, burst: 42, client: 54 },
      },
      {
        name: "Meta・社員密着ショート",
        horse: "シャインミッチャク",
        odds: 5.7,
        media: "Meta",
        setup: "若手社員 / 職場風景 / 興味形成",
        allocation: "動画60%・静止画25%・リマケ15%",
        stats: { fit: 66, stability: 54, burst: 78, client: 70 },
      },
      {
        name: "Google検索・地域求人ワード",
        horse: "チイキキュウジン",
        odds: 4.6,
        media: "Google",
        setup: "地域名x職種 / 応募CV / 夜間配信",
        allocation: "検索70%・夜間20%・除外10%",
        stats: { fit: 75, stability: 72, burst: 46, client: 58 },
      },
      {
        name: "TikTok・工場あるある",
        horse: "コウジョウアルアル",
        odds: 15.8,
        media: "TikTok",
        setup: "あるある動画 / コメント重視 / 認知突破",
        allocation: "あるある85%・コメント追撃15%",
        stats: { fit: 48, stability: 36, burst: 96, client: 66 },
      },
    ],
    incidents: [
      {
        type: "社長カットイン",
        title: "『家族みたい』コピーを強制採用",
        body: "社長満足度は上がる。応募意欲は少し静かになる。",
        effect: { client: 18, fit: -8 },
      },
      {
        type: "現場事故",
        title: "撮影日に作業着が全員バラバラ",
        body: "リアルではあるが、採用広報としては少し情報量が強い。",
        effect: { burst: -8, stability: -6 },
      },
      {
        type: "求人市況",
        title: "近隣の大手が時給を上げた",
        body: "比較される。給与と導線が明確なプランだけ耐える。",
        effect: { fit: -7, stability: -7, client: -3 },
      },
    ],
  },
];

// どの案件でも起こりうる汎用ハプニング。毎レースここから抽選で混ざるため展開が毎回変わる。
const GENERIC_INCIDENTS = [
  {
    type: "計測事故",
    title: "GTMのタグが誰かの『検証』で止まっていた",
    body: "コンバージョンが3時間分消失。学習がリセット気味に。",
    effect: { fit: -6, stability: -9 },
  },
  {
    type: "媒体アップデート",
    title: "入札アルゴリズムがサイレント変更",
    body: "リリースノートには何も書いていない。挙動だけが変わる。",
    effect: { stability: -10, burst: 7 },
  },
  {
    type: "奇跡",
    title: "競合が予算を使い切って撤退",
    body: "オークションが突然ぬるくなる。CPCが静かに下がる。",
    effect: { fit: 7, burst: 8 },
  },
  {
    type: "クライアント横やり",
    title: "社長『バナーは全部赤にして』",
    body: "赤くなった。CTRは上がったのか下がったのか誰にも分からない。",
    effect: { client: 13, fit: -6 },
  },
  {
    type: "予算事故",
    title: "請求上限に到達して配信が夕方に停止",
    body: "カードの上限申請は明日以降。ゴールデンタイムが沈黙する。",
    effect: { burst: -12, stability: -5 },
  },
  {
    type: "代理店あるある",
    title: "レポート提出日とレース日が重なる",
    body: "運用者の集中力が資料作成に吸われる。微調整が止まる。",
    effect: { stability: -6, client: 6 },
  },
  {
    type: "奇跡",
    title: "インフルエンサーが勝手に紹介してくれた",
    body: "誰も依頼していない。指名検索とSNS流入が同時に伸びる。",
    effect: { burst: 12, client: 6 },
  },
];
