"use strict";

// ============================================================
// 案件データ / 理不尽イベントデータ
// 実在の案件を参考にしたフィクションです。実名は使用していません。
// 毎ゲーム、この中からランダムに5案件が出題されます。
// ============================================================

const CASES = [
  {
    client: "つばさ光テレビ",
    industry: "通信キャリア（光回線+TVバンドル）",
    kpi: "申込CPA 25,000円以内",
    budget: "月300万円",
    absurdity: "中",
    brief:
      "光回線とTVサービスのセット申込を増やしたい。本部からは『若年層にも刺さる施策を』、現場からは『結局申し込むのは50代』という声。どちらも正しい。",
    plans: [
      {
        name: "Google検索・回線乗換ワード",
        horse: "ヒカリケンサクオウ",
        odds: 2.4,
        media: "Google",
        setup: "乗換/工事費ワード / 申込CV / 指名防衛",
        allocation: "検索70%・指名20%・検証10%",
        stats: { fit: 85, stability: 81, burst: 48, client: 64 },
      },
      {
        name: "YDA・比較検討層リターゲ",
        horse: "ヤフーオイコミ",
        odds: 4.8,
        media: "YDA",
        setup: "比較サイト閲覧層 / リタゲ厚め / 静止画",
        allocation: "リタゲ55%・類似30%・検証15%",
        stats: { fit: 72, stability: 66, burst: 62, client: 58 },
      },
      {
        name: "YouTube・工事レポ動画",
        horse: "ドウガコウジチュウ",
        odds: 7.5,
        media: "YouTube",
        setup: "開通までの流れ動画 / 認知〜検討 / CPV重視",
        allocation: "動画75%・検索追撃25%",
        stats: { fit: 60, stability: 58, burst: 70, client: 68 },
      },
      {
        name: "TVer・コネクテッドTV配信",
        horse: "チャノマセンリョウ",
        odds: 13.0,
        media: "TVer",
        setup: "CTV面 / 世帯リーチ / テレビ画面で完結訴求",
        allocation: "CTV85%・計測検証15%",
        stats: { fit: 50, stability: 44, burst: 88, client: 74 },
      },
    ],
    incidents: [
      {
        type: "本部横やり",
        title: "『若年層比率をKPIに追加で』",
        body: "申込は取れているのに、急に年齢構成の説明資料が必要になる。",
        effect: { client: 14, fit: -8 },
      },
      {
        type: "計測事故",
        title: "申込フォーム改修でCVタグが外れる",
        body: "改修担当は悪くない。連絡が来なかっただけ。学習が迷子になる。",
        effect: { stability: -14, fit: -5 },
      },
      {
        type: "奇跡",
        title: "引っ越しシーズンが前倒しで到来",
        body: "回線需要が自然増。刈り取り系が静かに伸びる。",
        effect: { fit: 9, stability: 6 },
      },
    ],
  },
  {
    client: "オンライン専用プラン ぽけっとS",
    industry: "通信（オンライン専用格安プラン）",
    kpi: "新規回線 月1,500件",
    budget: "月200万円",
    absurdity: "高",
    brief:
      "店舗もサポートも削ったオンライン専用プラン。『SNSでバズらせて獲得もしたい』という欲張り要件。バズと獲得は基本的に別の生き物である。",
    plans: [
      {
        name: "X・トレンド連動ポスト広告",
        horse: "トレンドイッキ",
        odds: 3.4,
        media: "X",
        setup: "トレンド便乗 / 自虐系コピー / 拡散狙い",
        allocation: "ポスト広告70%・反応追撃30%",
        stats: { fit: 68, stability: 52, burst: 86, client: 72 },
      },
      {
        name: "Google検索・料金比較ワード",
        horse: "シメイガリホンメイ",
        odds: 2.6,
        media: "Google",
        setup: "料金比較/乗換 / 申込CV / 除外徹底",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 84, stability: 80, burst: 46, client: 56 },
      },
      {
        name: "LINE・友だち追加からナーチャリング",
        horse: "ミドリノコウテイ",
        odds: 5.5,
        media: "LINE",
        setup: "友だち追加 / 配信で教育 / 乗換ハードル低減",
        allocation: "友だち追加60%・配信30%・検証10%",
        stats: { fit: 70, stability: 68, burst: 54, client: 60 },
      },
      {
        name: "TikTok・料金プラン解説ショート",
        horse: "ジーゼットダッシュ",
        odds: 9.8,
        media: "TikTok",
        setup: "早口解説 / コメント欄が本体 / 若年層直撃",
        allocation: "ショート90%・予備10%",
        stats: { fit: 52, stability: 40, burst: 94, client: 62 },
      },
    ],
    incidents: [
      {
        type: "炎上未遂",
        title: "自虐コピーが一部で燃えかける",
        body: "拡散はした。ポジティブとは言っていない。広報が会議を招集。",
        effect: { burst: -12, client: -8, stability: -4 },
      },
      {
        type: "競合動向",
        title: "競合が同日に値下げを発表",
        body: "比較表が一晩で古くなる。検索ワードの意図が変わる。",
        effect: { fit: -9, stability: -6 },
      },
      {
        type: "奇跡",
        title: "解説ショートがなぜか跳ねる",
        body: "投稿3本目にして急にアルゴリズムに愛される。SNS勢が加速。",
        effect: { burst: 15, client: 7 },
      },
    ],
  },
  {
    client: "スポーツ配信 スポマックスLIVE",
    industry: "動画配信サービス（スポーツ）",
    kpi: "無料トライアル登録CPA 4,000円以内",
    budget: "月500万円",
    absurdity: "中",
    brief:
      "開幕戦に向けて無料トライアルを最大化したい。ただし『解約前提のユーザーはいらない』という難しい注文つき。試合日程で需要が乱高下する。",
    plans: [
      {
        name: "Meta・名場面リール配信",
        horse: "メタメイバメン",
        odds: 3.2,
        media: "Facebook/Instagram",
        setup: "ハイライト風リール / 広め配信 / 登録LP直送",
        allocation: "リール65%・静止画20%・リタゲ15%",
        stats: { fit: 78, stability: 64, burst: 74, client: 58 },
      },
      {
        name: "Google検索・観戦方法ワード",
        horse: "カンセンケンサク",
        odds: 2.9,
        media: "Google",
        setup: "『試合 視聴方法』ワード / 需要刈り取り",
        allocation: "検索80%・指名10%・検証10%",
        stats: { fit: 84, stability: 76, burst: 50, client: 54 },
      },
      {
        name: "ABEMA Ads・スポーツ好き面",
        horse: "レンダンアベマ",
        odds: 8.6,
        media: "ABEMA Ads",
        setup: "スポーツコンテンツ隣接面 / 動画15秒",
        allocation: "動画80%・検証20%",
        stats: { fit: 62, stability: 56, burst: 72, client: 66 },
      },
      {
        name: "The Trade Desk・CTV一点勝負",
        horse: "リビングジャック",
        odds: 14.5,
        media: "The Trade Desk",
        setup: "CTV / 世帯ターゲティング / 大画面で臨場感",
        allocation: "CTV90%・計測10%",
        stats: { fit: 48, stability: 42, burst: 90, client: 76 },
      },
    ],
    incidents: [
      {
        type: "配信事故",
        title: "注目カードが雨天中止",
        body: "需要予測が崩壊。検索ボリュームが蒸発する。",
        effect: { fit: -10, burst: -8 },
      },
      {
        type: "権利カットイン",
        title: "名場面素材の使用範囲に指摘",
        body: "一番強いクリエイティブが差し替えに。リーガルは正しい。つらいだけ。",
        effect: { burst: -14, stability: 4 },
      },
      {
        type: "奇跡",
        title: "無名の若手選手が大活躍",
        body: "SNSがお祭りに。ハイライト系クリエイティブが火を吹く。",
        effect: { burst: 16, fit: 6 },
      },
    ],
  },
  {
    client: "駅前英会話 ブライト",
    industry: "英会話スクール",
    kpi: "無料体験予約 月60件",
    budget: "月90万円",
    absurdity: "中",
    brief:
      "4月の入会シーズンに向けて無料体験を集めたい。校長は『英語で人生が広がる』系の情緒訴求が好きだが、予約が取れるのはいつも料金訴求である。",
    plans: [
      {
        name: "Google検索・地域×英会話",
        horse: "エキマエホンメイ",
        odds: 2.5,
        media: "Google",
        setup: "地域名×英会話 / 体験予約CV / 電話併用",
        allocation: "検索75%・マップ15%・検証10%",
        stats: { fit: 86, stability: 80, burst: 44, client: 58 },
      },
      {
        name: "Meta・リード広告で体験予約",
        horse: "リードスグトレル",
        odds: 4.3,
        media: "Facebook/Instagram",
        setup: "フォーム一体型 / 学習意欲層 / 入力3項目",
        allocation: "リード広告70%・リタゲ20%・検証10%",
        stats: { fit: 74, stability: 62, burst: 66, client: 54 },
      },
      {
        name: "SmartNews・学び直し記事面",
        horse: "スマニューシブトイ",
        odds: 8.0,
        media: "SmartNews",
        setup: "記事風クリエイティブ / 30-50代 / 朝夕配信",
        allocation: "記事面80%・検証20%",
        stats: { fit: 58, stability: 60, burst: 62, client: 62 },
      },
      {
        name: "Taboola・体験談ネイティブ枠",
        horse: "タイケンダンナガレ",
        odds: 15.5,
        media: "Taboola",
        setup: "体験談記事LP / ネイティブ面 / 低CPC大量流入",
        allocation: "ネイティブ85%・LP改善15%",
        stats: { fit: 46, stability: 40, burst: 88, client: 50 },
      },
    ],
    incidents: [
      {
        type: "校長カットイン",
        title: "『人生が広がる』コピーを強制採用",
        body: "情緒は満たされた。クリック率は静かになった。",
        effect: { client: 15, fit: -7 },
      },
      {
        type: "現場事故",
        title: "体験枠が講師のシフト都合で半減",
        body: "広告は好調なのに予約枠がない。機会損失が数字に出る。",
        effect: { stability: -12, burst: -6 },
      },
      {
        type: "市況",
        title: "大手が春の入会金無料を開始",
        body: "比較される。料金と導線が明確なプランだけ耐える。",
        effect: { fit: -7, stability: -5, client: -4 },
      },
    ],
  },
  {
    client: "まもりあ生命 ネット保険",
    industry: "生命保険（通信系バンドル）",
    kpi: "資料請求CPA 12,000円以内",
    budget: "月150万円",
    absurdity: "高",
    brief:
      "通信契約とセットの割引が売りのネット生保。金融広告なので審査は厳しく、表現の自由度は低い。それでいて『もっとエモく』という要望が来ている。",
    plans: [
      {
        name: "Yahoo!検索・保険見直しワード",
        horse: "ミナオシケンサク",
        odds: 2.8,
        media: "Yahoo!",
        setup: "見直し/比較ワード / 資料請求CV / 40-60代",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 84, stability: 78, burst: 46, client: 60 },
      },
      {
        name: "GDN・ライフイベント配信",
        horse: "ジーディーエヌコツコツ",
        odds: 4.6,
        media: "GDN",
        setup: "結婚/出産インテント / 静止画 / CPC抑制",
        allocation: "インテント60%・リタゲ25%・検証15%",
        stats: { fit: 72, stability: 70, burst: 52, client: 56 },
      },
      {
        name: "LINE・家計相談トーク導線",
        horse: "カケイボトーク",
        odds: 6.2,
        media: "LINE",
        setup: "友だち追加→家計診断 / ナーチャリング",
        allocation: "友だち追加55%・配信30%・検証15%",
        stats: { fit: 64, stability: 62, burst: 58, client: 66 },
      },
      {
        name: "Outbrain・読み物LP勝負",
        horse: "ヨミモノギャンブル",
        odds: 17.0,
        media: "Outbrain",
        setup: "保険コラムLP / ネイティブ面 / 情緒訴求全開",
        allocation: "ネイティブ85%・LP検証15%",
        stats: { fit: 44, stability: 38, burst: 90, client: 70 },
      },
    ],
    incidents: [
      {
        type: "審査カットイン",
        title: "『安心』の根拠提示を求められる",
        body: "金融広告の審査は正確である。締切には冷たいが。",
        effect: { stability: -16, burst: -6 },
      },
      {
        type: "クライアント横やり",
        title: "『もっとエモい動画に差し替えて』",
        body: "エモさは審査を通らない。通る範囲のエモさが爆誕する。",
        effect: { client: 14, stability: -8 },
      },
      {
        type: "奇跡",
        title: "家計見直し特集がテレビで放送",
        body: "『保険 見直し』の検索が急増。刈り取り系が潤う。",
        effect: { fit: 10, stability: 5 },
      },
    ],
  },
  {
    client: "あおぞら県 観光誘客キャンペーン",
    industry: "自治体・官公庁",
    kpi: "特設サイト訪問 30万セッション",
    budget: "期間3ヶ月で400万円",
    absurdity: "極",
    brief:
      "県の観光キャンペーン。KPIはセッション数だが、本当のKPIは『議会で説明できること』。ブランドセーフティ要件が民間案件の3倍厳しい。",
    plans: [
      {
        name: "YouTube・観光PR動画",
        horse: "ケンチョウドウガ",
        odds: 3.0,
        media: "YouTube",
        setup: "絶景ドローン動画 / 認知拡大 / 面の説明が容易",
        allocation: "動画80%・検索追撃20%",
        stats: { fit: 78, stability: 76, burst: 56, client: 74 },
      },
      {
        name: "DV360・PMPで面を完全指定",
        horse: "ピーエムピーカタメ",
        odds: 4.4,
        media: "DV360",
        setup: "PMP取引 / ホワイトリスト面のみ / 議会対応万全",
        allocation: "PMP85%・レポート整備15%",
        stats: { fit: 70, stability: 82, burst: 42, client: 80 },
      },
      {
        name: "X・ご当地バズ企画",
        horse: "バズラセタガリ",
        odds: 6.8,
        media: "X",
        setup: "ご当地ネタ / ハッシュタグ企画 / 拡散狙い",
        allocation: "ポスト広告70%・企画30%",
        stats: { fit: 58, stability: 46, burst: 88, client: 52 },
      },
      {
        name: "Teads・上品なインリード動画",
        horse: "ジョウヒンインリード",
        odds: 10.5,
        media: "Teads",
        setup: "プレミア媒体面 / インリード動画 / 品位重視",
        allocation: "インリード80%・検証20%",
        stats: { fit: 52, stability: 64, burst: 60, client: 78 },
      },
    ],
    incidents: [
      {
        type: "議会カットイン",
        title: "『この広告費の妥当性は』と質問が出る",
        body: "資料作成に運用者の魂が3日吸われる。入札調整が止まる。",
        effect: { stability: -10, client: 8 },
      },
      {
        type: "ブランドセーフティ",
        title: "配信面リストの再提出を求められる",
        body: "面が絞られる。安全だが、リーチも安全な数字になる。",
        effect: { burst: -12, client: 10 },
      },
      {
        type: "奇跡",
        title: "県の名物がドラマの舞台に",
        body: "誰も予算を使っていないのに検索が伸びる。行政の勝利。",
        effect: { fit: 12, burst: 8 },
      },
    ],
  },
  {
    client: "新作RPG グリモワール学園",
    industry: "ゲーム（コンシューマ新作）",
    kpi: "発売週DL数 + 予約数",
    budget: "発売前後6週で800万円",
    absurdity: "高",
    brief:
      "魔法学園が舞台の大型新作RPG。ファンの熱量は高いが、ネタバレと炎上のリスクも高い。海外本社からは『グローバル統一クリエイティブで』という無茶が届いている。",
    plans: [
      {
        name: "YouTube・トレーラー指名配信",
        horse: "トレーラーホンメイ",
        odds: 2.7,
        media: "YouTube",
        setup: "公式トレーラー / ゲーム実況隣接面 / 予約CV",
        allocation: "動画70%・検索指名20%・検証10%",
        stats: { fit: 84, stability: 74, burst: 58, client: 62 },
      },
      {
        name: "TikTok・プレイ切り抜き",
        horse: "キリヌキマホウ",
        odds: 4.5,
        media: "TikTok",
        setup: "15秒プレイ映像 / 音ハメ編集 / 拡散狙い",
        allocation: "ショート80%・反応追撃20%",
        stats: { fit: 68, stability: 50, burst: 92, client: 56 },
      },
      {
        name: "X・ファンアート文脈参入",
        horse: "コスプレバズ",
        odds: 7.2,
        media: "X",
        setup: "ファンコミュニティ文脈 / UGC活性化",
        allocation: "ポスト広告65%・企画35%",
        stats: { fit: 60, stability: 48, burst: 84, client: 58 },
      },
      {
        name: "ASA・ストア検索一点突破",
        horse: "ストアイッテン",
        odds: 12.0,
        media: "ASA",
        setup: "App Store検索 / 関連タイトル指名 / DL直結",
        allocation: "ASA90%・キーワード検証10%",
        stats: { fit: 54, stability: 66, burst: 52, client: 48 },
      },
    ],
    incidents: [
      {
        type: "本社カットイン",
        title: "グローバル統一バナーの使用を指示",
        body: "日本のファンに刺さらない色使い。ローカライズの意味を全員が考える。",
        effect: { client: 12, fit: -10 },
      },
      {
        type: "ネタバレ事故",
        title: "海外で発売が1日早く、実況が解禁",
        body: "重大ネタバレがトレンド入り。認知は上がった。複雑な気持ちで。",
        effect: { burst: 10, client: -8, stability: -6 },
      },
      {
        type: "奇跡",
        title: "有名実況者が自腹で48時間配信",
        body: "依頼していない。愛だけがそこにある。UGC系が大加速。",
        effect: { burst: 16, fit: 7 },
      },
    ],
  },
  {
    client: "ふんわりプレミア柔軟剤",
    industry: "日用品メーカー（新商品）",
    kpi: "EC売上 + 店頭想起",
    budget: "発売月450万円",
    absurdity: "中",
    brief:
      "香りが12時間続く新作柔軟剤。ECでの売上と店頭での想起を同時に求められている。宣伝部は『デジタルでテレビ並みのリーチを』と言う。予算はテレビの10分の1である。",
    plans: [
      {
        name: "Amazon Ads・カテゴリ刈り取り",
        horse: "カゴオチシラズ",
        odds: 2.6,
        media: "Amazon",
        setup: "柔軟剤カテゴリ / スポンサープロダクト / 購入直結",
        allocation: "SP70%・ブランド枠20%・検証10%",
        stats: { fit: 86, stability: 80, burst: 44, client: 54 },
      },
      {
        name: "Meta・香り体験リール",
        horse: "カオリバズーカ",
        odds: 4.2,
        media: "Facebook/Instagram",
        setup: "香り擬人化リール / 主婦層 / EC送客",
        allocation: "リール65%・静止画20%・リタゲ15%",
        stats: { fit: 72, stability: 60, burst: 78, client: 64 },
      },
      {
        name: "Gunosy・比較記事ネイティブ",
        horse: "キジメンジミー",
        odds: 9.4,
        media: "Gunosy",
        setup: "柔軟剤比較記事 / ネイティブ面 / 低CPC",
        allocation: "記事面80%・LP改善20%",
        stats: { fit: 54, stability: 58, burst: 60, client: 52 },
      },
      {
        name: "ChatGPT広告・新チャネル人柱",
        horse: "エーアイサキガケ",
        odds: 23.0,
        media: "ChatGPT",
        setup: "会話文脈ターゲティング / 誰も正解を知らない",
        allocation: "新枠90%・祈り10%",
        stats: { fit: 42, stability: 34, burst: 96, client: 72 },
      },
    ],
    incidents: [
      {
        type: "宣伝部横やり",
        title: "『とにかくリーチの数字を大きく』",
        body: "獲得系の予算が認知系へ移動。ECの数字が静かになる。",
        effect: { client: 12, fit: -9 },
      },
      {
        type: "供給事故",
        title: "EC在庫が想定より早く欠品",
        body: "広告は絶好調。買えないだけ。機会損失レポートが生まれる。",
        effect: { burst: -14, stability: -6 },
      },
      {
        type: "奇跡",
        title: "香りマニアの投稿がバズる",
        body: "『12時間持続は本当か検証してみた』が拡散。指名検索が急増。",
        effect: { burst: 12, fit: 8 },
      },
    ],
  },
  {
    client: "音楽サブスク オトメグリMusic",
    industry: "音楽ストリーミング",
    kpi: "無料トライアル→有料転換 月8,000件",
    budget: "月350万円",
    absurdity: "中",
    brief:
      "1億曲聴き放題のサブスク。若年層は競合に固まっており、狙いは『昔CDを買っていた層』。ただし本部は若者向けクリエイティブしか承認しない。",
    plans: [
      {
        name: "TikTok・プレイリスト紹介",
        horse: "プレイリストバズ",
        odds: 3.1,
        media: "TikTok",
        setup: "懐メロプレイリスト / 音源そのまま訴求",
        allocation: "ショート75%・反応追撃25%",
        stats: { fit: 76, stability: 58, burst: 84, client: 60 },
      },
      {
        name: "YouTube・MV前アドロール",
        horse: "エムブイマエオキ",
        odds: 2.8,
        media: "Youtube",
        setup: "音楽動画隣接 / スキップ可 / 無料訴求",
        allocation: "動画70%・検索指名20%・検証10%",
        stats: { fit: 82, stability: 74, burst: 54, client: 58 },
      },
      {
        name: "X・懐メロ世代の共感ポスト",
        horse: "ナツメロキョウカン",
        odds: 6.4,
        media: "X",
        setup: "『この曲知ってたら同世代』 / 共感拡散",
        allocation: "ポスト広告70%・企画30%",
        stats: { fit: 62, stability: 52, burst: 80, client: 64 },
      },
      {
        name: "ASA・ストア検索刈り取り",
        horse: "ストアマチブセ",
        odds: 10.0,
        media: "ASA",
        setup: "『音楽 アプリ』検索 / 競合指名も入札",
        allocation: "ASA85%・キーワード検証15%",
        stats: { fit: 58, stability: 68, burst: 46, client: 48 },
      },
    ],
    incidents: [
      {
        type: "権利カットイン",
        title: "広告で使える楽曲リストが急に縮む",
        body: "一番エモい曲が使用不可に。エモくない曲でエモさを演出する仕事が始まる。",
        effect: { burst: -13, stability: -4 },
      },
      {
        type: "本部横やり",
        title: "『若者向けトーンに統一して』",
        body: "ターゲットは40代なのに。クリエイティブと配信面が静かにすれ違う。",
        effect: { client: 12, fit: -10 },
      },
      {
        type: "奇跡",
        title: "懐かしバンドの再結成が発表",
        body: "『あの曲 サブスク』検索が爆増。プレイリスト系が急加速。",
        effect: { fit: 10, burst: 10 },
      },
    ],
  },
  {
    client: "サクッとPay 加盟店開拓",
    industry: "QR決済（BtoB）",
    kpi: "加盟店申込 月400件",
    budget: "月180万円",
    absurdity: "高",
    brief:
      "個人商店にQR決済端末を導入してもらいたい。ターゲットは60代の店主。デジタル広告でデジタルが苦手な人に届けるという、根本的な矛盾を抱えている。",
    plans: [
      {
        name: "Google検索・キャッシュレス補助金",
        horse: "ホジョキンケンサク",
        odds: 2.7,
        media: "Google",
        setup: "補助金/手数料ワード / 資料請求CV",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 84, stability: 78, burst: 46, client: 58 },
      },
      {
        name: "LinkedIn・商工会関係者ねらい",
        horse: "ショウコウカイジン",
        odds: 7.8,
        media: "LinkedIn",
        setup: "経営層/団体職員 / ホワイトペーパー",
        allocation: "役職配信80%・検証20%",
        stats: { fit: 60, stability: 62, burst: 50, client: 76 },
      },
      {
        name: "YDA・商店主の生活面配信",
        horse: "ショウテンガイキリコミ",
        odds: 4.9,
        media: "YDA",
        setup: "50-60代 / ニュース面 / 導入事例訴求",
        allocation: "ディスプレイ70%・リタゲ20%・検証10%",
        stats: { fit: 70, stability: 68, burst: 58, client: 56 },
      },
      {
        name: "X・レジ前あるあるネタ",
        horse: "レジマエアルアル",
        odds: 12.5,
        media: "X",
        setup: "『現金のみ』あるある / 話題化して間接送客",
        allocation: "ポスト広告75%・追撃25%",
        stats: { fit: 50, stability: 44, burst: 88, client: 54 },
      },
    ],
    incidents: [
      {
        type: "営業カットイン",
        title: "『Webからの申込は質が低い』説が浮上",
        body: "訪問営業部隊とデジタルの縄張り争いが勃発。計測定義会議が3時間。",
        effect: { fit: -8, client: -10, stability: 4 },
      },
      {
        type: "制度変更",
        title: "補助金の申請要件がしれっと改定",
        body: "LPの訴求が一晩で古くなる。修正デザインの納期は1週間後。",
        effect: { stability: -12, fit: -6 },
      },
      {
        type: "奇跡",
        title: "テレビでキャッシュレス特集が放送",
        body: "『QR決済 導入』の検索が急増。刈り取り系が静かに潤う。",
        effect: { fit: 10, stability: 6 },
      },
    ],
  },
  {
    client: "そよかぜ銀行",
    industry: "ネット銀行",
    kpi: "口座開設 月5,000件",
    budget: "月400万円",
    absurdity: "中",
    brief:
      "金利とポイント還元が売りのネット銀行。金融庁ガイドラインと社内審査の二重チェックで、承認されたコピーはいつも角が取れて丸くなる。",
    plans: [
      {
        name: "Yahoo!検索・金利比較ワード",
        horse: "キンリケンサク",
        odds: 2.5,
        media: "Yahoo!",
        setup: "金利/口座開設ワード / 40-60代厚め",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 86, stability: 80, burst: 44, client: 60 },
      },
      {
        name: "Criteo・比較サイト離脱リタゲ",
        horse: "リタゲシツコイ",
        odds: 4.4,
        media: "Criteo",
        setup: "比較サイト閲覧層 / 動的バナー / 追跡",
        allocation: "リタゲ80%・類似20%",
        stats: { fit: 74, stability: 70, burst: 56, client: 50 },
      },
      {
        name: "LINE・ポイ活文脈で訴求",
        horse: "ポイカツコウテイ",
        odds: 6.0,
        media: "LINE",
        setup: "ポイ活層 / 還元率訴求 / 友だち追加",
        allocation: "配信60%・友だち追加30%・検証10%",
        stats: { fit: 66, stability: 60, burst: 72, client: 56 },
      },
      {
        name: "SmartNews・マネー記事面",
        horse: "マネーキジワク",
        odds: 11.0,
        media: "SmartNews",
        setup: "経済記事隣接 / 記事風 / 朝の通勤時間",
        allocation: "記事面80%・検証20%",
        stats: { fit: 54, stability: 58, burst: 66, client: 58 },
      },
    ],
    incidents: [
      {
        type: "審査カットイン",
        title: "『業界No.1』表記に根拠資料の提出命令",
        body: "No.1の定義を巡る社内議論が白熱。広告は静かに停止している。",
        effect: { stability: -15, burst: -5 },
      },
      {
        type: "市況",
        title: "メガバンクが急に金利を引き上げ",
        body: "比較優位が縮む。還元率訴求だけが頼りになる。",
        effect: { fit: -9, client: -5 },
      },
      {
        type: "奇跡",
        title: "新NISA特集で口座開設ブーム再燃",
        body: "『ネット銀行 おすすめ』検索が急増。刈り取り系が伸びる。",
        effect: { fit: 11, stability: 5 },
      },
    ],
  },
  {
    client: "スマイルカード GOLD",
    industry: "クレジットカード",
    kpi: "新規発行CPA 8,000円以内",
    budget: "月250万円",
    absurdity: "中",
    brief:
      "年会費無料のゴールドカード。入会特典ポイントで釣ると質が下がり、質を求めると件数が出ない、クレカ広告の永遠のジレンマを今月も生きている。",
    plans: [
      {
        name: "Google検索・カード比較ワード",
        horse: "ヒカクケンサクオウ",
        odds: 2.6,
        media: "Google",
        setup: "ゴールドカード比較 / 発行CV / 除外厳選",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 85, stability: 79, burst: 46, client: 58 },
      },
      {
        name: "Meta・特典ポイント訴求",
        horse: "トクテンバラマキ",
        odds: 4.0,
        media: "Facebook/Instagram",
        setup: "入会特典 / 類似拡張 / 動的クリエイティブ",
        allocation: "類似55%・興味30%・リタゲ15%",
        stats: { fit: 72, stability: 62, burst: 76, client: 52 },
      },
      {
        name: "popIn・記事レコメンド面",
        horse: "キジシタレコメン",
        odds: 9.2,
        media: "popIn",
        setup: "記事下レコメンド / マネー系記事LP",
        allocation: "ネイティブ80%・LP検証20%",
        stats: { fit: 56, stability: 54, burst: 70, client: 50 },
      },
      {
        name: "GDN・ポイ活ブログ面",
        horse: "ブログメンジミー",
        odds: 6.8,
        media: "GDN",
        setup: "ポイ活/節約ブログ面 / CPC抑制",
        allocation: "プレースメント70%・リタゲ20%・検証10%",
        stats: { fit: 64, stability: 66, burst: 58, client: 54 },
      },
    ],
    incidents: [
      {
        type: "与信カットイン",
        title: "審査基準が今月から静かに厳格化",
        body: "申込は取れるのに発行率が下がる。CPAの定義を巡り会議が発生。",
        effect: { fit: -10, stability: -6 },
      },
      {
        type: "クライアント横やり",
        title: "『特典訴求はブランドが安く見える』",
        body: "一番CVRが高い訴求が封印される。上品なバナーが残った。",
        effect: { client: 14, burst: -12 },
      },
      {
        type: "奇跡",
        title: "人気ポイ活系の動画で紹介される",
        body: "紹介リンクは別会社のものだったが、指名検索は増えた。世界は複雑。",
        effect: { fit: 8, burst: 9 },
      },
    ],
  },
  {
    client: "タブポッドPro 新モデル",
    industry: "PC・タブレット",
    kpi: "発売月販売台数 + 指名検索数",
    budget: "発売月600万円",
    absurdity: "中",
    brief:
      "着脱式キーボードの2in1新モデル。グローバル本社の素材規定が厳しく、使える画像は白背景の製品写真のみ。日本チームは今日も工夫で戦っている。",
    plans: [
      {
        name: "Microsoft広告・ビジネス検索面",
        horse: "シゴトバケンサク",
        odds: 3.5,
        media: "Microsoft",
        setup: "業務PC/買い替えワード / 法人個人両にらみ",
        allocation: "検索70%・オーディエンス20%・検証10%",
        stats: { fit: 76, stability: 74, burst: 50, client: 62 },
      },
      {
        name: "YouTube・レビュー動画隣接",
        horse: "レビューナラビ",
        odds: 2.9,
        media: "Youtube",
        setup: "ガジェットレビュー隣接 / 比較検討層",
        allocation: "動画70%・検索追撃20%・検証10%",
        stats: { fit: 82, stability: 70, burst: 58, client: 56 },
      },
      {
        name: "Amazon Ads・カテゴリ指名",
        horse: "カートチョッコウ",
        odds: 4.6,
        media: "Amazon",
        setup: "ノートPCカテゴリ / 競合商品面 / 購入直結",
        allocation: "SP65%・ブランド枠25%・検証10%",
        stats: { fit: 74, stability: 72, burst: 52, client: 50 },
      },
      {
        name: "X・ガジェット民の祭りに参加",
        horse: "ガジェットマツリ",
        odds: 10.5,
        media: "X",
        setup: "発売日実況 / 開封の儀文脈 / UGC狙い",
        allocation: "ポスト広告70%・企画30%",
        stats: { fit: 54, stability: 46, burst: 90, client: 58 },
      },
    ],
    incidents: [
      {
        type: "本社カットイン",
        title: "白背景写真以外の使用が禁止に",
        body: "ライフスタイル訴求が全滅。白い背景に想いを込める仕事が始まる。",
        effect: { burst: -12, client: 8 },
      },
      {
        type: "供給事故",
        title: "初回出荷分が想定より少ない",
        body: "『在庫僅少』は煽りではなく事実になった。広告を絞る判断が求められる。",
        effect: { burst: -10, stability: -6 },
      },
      {
        type: "奇跡",
        title: "辛口レビュアーがまさかの高評価",
        body: "『正直、期待してなかったけど』から始まる動画が拡散。指名が伸びる。",
        effect: { fit: 9, burst: 11 },
      },
    ],
  },
  {
    client: "うみかぜリゾートパーク",
    industry: "レジャー・テーマパーク",
    kpi: "夏季チケットEC販売 3万枚",
    budget: "夏季3ヶ月500万円",
    absurdity: "高",
    brief:
      "海沿いの中規模テーマパーク。夏の集客が年間売上の6割を占める。天気に売上が支配されるのに、KPIは天気を考慮してくれない。",
    plans: [
      {
        name: "Instagram・映えスポットリール",
        horse: "バエスポリール",
        odds: 2.8,
        media: "Facebook/Instagram",
        setup: "映え写真リール / ファミリー&カップル",
        allocation: "リール65%・静止画20%・リタゲ15%",
        stats: { fit: 82, stability: 66, burst: 76, client: 62 },
      },
      {
        name: "TVer・ファミリー番組面",
        horse: "チャノマファミリー",
        odds: 5.8,
        media: "TVer",
        setup: "ファミリー向け番組面 / 世帯リーチ",
        allocation: "CTV含む動画80%・検証20%",
        stats: { fit: 64, stability: 60, burst: 68, client: 72 },
      },
      {
        name: "Gunosy・おでかけ記事面",
        horse: "オデカケキジワク",
        odds: 9.0,
        media: "Gunosy",
        setup: "週末おでかけ記事 / 金曜夕方配信強化",
        allocation: "記事面75%・検証25%",
        stats: { fit: 56, stability: 58, burst: 62, client: 54 },
      },
      {
        name: "UNIVERSE・若年層アプリ面",
        horse: "ワカモノアミアミ",
        odds: 13.5,
        media: "UNIVERSE",
        setup: "若年層アプリ面 / 学割訴求 / 動画",
        allocation: "アプリ面80%・検証20%",
        stats: { fit: 48, stability: 46, burst: 84, client: 56 },
      },
    ],
    incidents: [
      {
        type: "天候事故",
        title: "週末のたびに台風が接近",
        body: "予約キャンセルの嵐。広告は完璧だった。天気以外は。",
        effect: { fit: -10, stability: -8 },
      },
      {
        type: "現場カットイン",
        title: "目玉アトラクションが点検で運休",
        body: "メインビジュアルの乗り物が乗れない。注釈テキストが増えていく。",
        effect: { burst: -12, client: -6 },
      },
      {
        type: "奇跡",
        title: "パークの猫がSNSで大人気に",
        body: "誰も飼っていない。いつからかいる。公式より人気がある。",
        effect: { burst: 14, client: 8 },
      },
    ],
  },
  {
    client: "はるかぜホーム",
    industry: "住宅メーカー",
    kpi: "モデルハウス来場予約 月80組",
    budget: "月220万円",
    absurdity: "中",
    brief:
      "郊外型の注文住宅メーカー。検討期間が長い商材なのに、評価は今月の来場数で決まる。『未来の検討層』への投資は、いつも後回しにされる。",
    plans: [
      {
        name: "Google検索・地域×注文住宅",
        horse: "チュウモンジュウタク",
        odds: 2.7,
        media: "Google",
        setup: "地域×住宅ワード / 来場予約CV",
        allocation: "検索70%・マップ15%・検証15%",
        stats: { fit: 84, stability: 78, burst: 44, client: 60 },
      },
      {
        name: "YDA・住宅検討層ターゲ",
        horse: "マドリナガメ",
        odds: 4.5,
        media: "YDA",
        setup: "住宅検討セグメント / 間取り訴求バナー",
        allocation: "ディスプレイ65%・リタゲ25%・検証10%",
        stats: { fit: 72, stability: 68, burst: 56, client: 58 },
      },
      {
        name: "LINE・子育て世帯配信",
        horse: "コソダテセタイ",
        odds: 6.5,
        media: "LINE",
        setup: "子育て層 / 収納・家事動線訴求",
        allocation: "配信70%・友だち追加20%・検証10%",
        stats: { fit: 64, stability: 62, burst: 62, client: 64 },
      },
      {
        name: "NativeOcean・ルームツアー記事",
        horse: "ルームツアーナガシ",
        odds: 12.0,
        media: "NativeOcean",
        setup: "ルームツアー記事LP / ネイティブ面",
        allocation: "ネイティブ80%・LP改善20%",
        stats: { fit: 50, stability: 48, burst: 78, client: 56 },
      },
    ],
    incidents: [
      {
        type: "営業カットイン",
        title: "『冷やかしの来場はいらない』",
        body: "来場の質を上げると数が減る。数を上げると営業が疲れる。無限ループ。",
        effect: { fit: -8, client: -8, stability: 5 },
      },
      {
        type: "市況",
        title: "住宅ローン金利の上昇が報道される",
        body: "検討層が一斉に様子見モードへ。CVまでの距離が伸びる。",
        effect: { fit: -8, stability: -6 },
      },
      {
        type: "奇跡",
        title: "施主のルームツアー動画がバズる",
        body: "依頼していないのに最高の宣伝。指名検索と来場予約が伸びる。",
        effect: { burst: 13, fit: 7 },
      },
    ],
  },
  {
    client: "ひざラクEX（第3類医薬品）",
    industry: "製薬・ヘルスケア",
    kpi: "EC定期購入 月2,000件",
    budget: "月280万円",
    absurdity: "極",
    brief:
      "ひざ関節痛向けの医薬品。効きそうな表現はだいたい薬機法に触れ、触れない表現はだいたい効かなそう。この狭い道を今日も歩く。",
    plans: [
      {
        name: "Yahoo!検索・症状ワード",
        horse: "ショウジョウケンサク",
        odds: 2.9,
        media: "Yahoo!",
        setup: "ひざ痛ワード / 50-70代 / EC直送",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 82, stability: 76, burst: 46, client: 56 },
      },
      {
        name: "ScaleOut・シニア面ディスプレイ",
        horse: "シニアメンハイシン",
        odds: 6.2,
        media: "ScaleOut",
        setup: "シニア閲覧面 / 大きな文字バナー",
        allocation: "ディスプレイ75%・リタゲ15%・検証10%",
        stats: { fit: 64, stability: 62, burst: 58, client: 54 },
      },
      {
        name: "SmartNews・健康記事面",
        horse: "ケンコウキジワク",
        odds: 4.7,
        media: "SmartNews",
        setup: "健康記事隣接 / 記事風 / 朝配信",
        allocation: "記事面75%・検証25%",
        stats: { fit: 70, stability: 64, burst: 64, client: 58 },
      },
      {
        name: "Outbrain・体験記事一点勝負",
        horse: "タイケンキジカケ",
        odds: 13.0,
        media: "Outbrain",
        setup: "体験談風記事LP / ネイティブ大量流入",
        allocation: "ネイティブ85%・LP検証15%",
        stats: { fit: 48, stability: 40, burst: 88, client: 52 },
      },
    ],
    incidents: [
      {
        type: "薬機法カットイン",
        title: "『スッと楽に』の『スッと』に指摘",
        body: "副詞ひとつで会議が開かれる。効能表現の許容範囲は今日も狭い。",
        effect: { burst: -14, stability: -6 },
      },
      {
        type: "媒体審査",
        title: "ビフォーアフター表現で審査落ち",
        body: "体験談LPが全面改修に。ライターの魂が2日消える。",
        effect: { stability: -12, fit: -5 },
      },
      {
        type: "奇跡",
        title: "健康番組でひざケア特集が放送",
        body: "『ひざ サプリ 薬』の検索が急増。症状ワードが刈り放題に。",
        effect: { fit: 12, stability: 5 },
      },
    ],
  },
  {
    client: "金色エール〈生〉",
    industry: "ビール・飲料",
    kpi: "新商品認知率 + EC/店頭連動",
    budget: "発売月700万円",
    absurdity: "中",
    brief:
      "10年ぶりの大型新ブランド。20歳未満への配信は厳禁、飲酒シーンの表現規制も多い。『若い世代にビール文化を』という願いと規制の間で今日も揺れる。",
    plans: [
      {
        name: "TVer・ゴールデン帯ドラマ面",
        horse: "オチャノマエース",
        odds: 3.0,
        media: "TVer",
        setup: "ドラマ面 / 年齢認証済み配信 / 15秒",
        allocation: "動画80%・検証20%",
        stats: { fit: 80, stability: 72, burst: 60, client: 70 },
      },
      {
        name: "ABEMA Ads・スポーツ観戦面",
        horse: "カンパイアベマ",
        odds: 4.8,
        media: "ABEMA Ads",
        setup: "格闘技/スポーツ面 / 乾杯シーン動画",
        allocation: "動画75%・検証25%",
        stats: { fit: 70, stability: 62, burst: 72, client: 62 },
      },
      {
        name: "X・発売日乾杯祭り",
        horse: "カンパイマツリ",
        odds: 6.6,
        media: "X",
        setup: "発売日ハッシュタグ / UGC乾杯投稿",
        allocation: "ポスト広告65%・企画35%",
        stats: { fit: 60, stability: 50, burst: 86, client: 58 },
      },
      {
        name: "Teads・プレミア誌面インリード",
        horse: "ジョウヒンインリード",
        odds: 11.5,
        media: "Teads",
        setup: "プレミアム媒体 / ブランドムービー30秒",
        allocation: "インリード80%・検証20%",
        stats: { fit: 50, stability: 60, burst: 58, client: 78 },
      },
    ],
    incidents: [
      {
        type: "規制カットイン",
        title: "飲酒シーンの秒数に社内基準が追加",
        body: "ゴクゴク音は2秒まで。編集チームが無言でタイムラインを詰める。",
        effect: { burst: -10, client: 8 },
      },
      {
        type: "供給事故",
        title: "売れすぎて出荷調整が発表される",
        body: "広告を止めるという広告史上最も贅沢な悩みが発生。",
        effect: { burst: -16, fit: -4, client: 10 },
      },
      {
        type: "奇跡",
        title: "居酒屋チェーンが勝手にフェア開催",
        body: "現場の判断が一番早い。乾杯投稿が自然発生する。",
        effect: { burst: 12, client: 6 },
      },
    ],
  },
  {
    client: "クリアきこえ補聴器",
    industry: "補聴器・医療機器",
    kpi: "無料聴力チェック予約 月300件",
    budget: "月160万円",
    absurdity: "高",
    brief:
      "本人は『まだ必要ない』と思っており、家族が先に検索する商材。ターゲットが二層構造なのに、LPはひとつしか作る予算がない。",
    plans: [
      {
        name: "Yahoo!検索・家族の検索を拾う",
        horse: "カゾクノケンサク",
        odds: 2.8,
        media: "Yahoo!",
        setup: "『親 聞こえ』系ワード / 予約CV",
        allocation: "検索75%・指名10%・検証15%",
        stats: { fit: 83, stability: 77, burst: 45, client: 58 },
      },
      {
        name: "GDN・シニア面大きめバナー",
        horse: "オオキメバナー",
        odds: 4.9,
        media: "GDN",
        setup: "シニア閲覧面 / 文字大きめ / 電話CV併用",
        allocation: "ディスプレイ70%・リタゲ20%・検証10%",
        stats: { fit: 70, stability: 68, burst: 52, client: 60 },
      },
      {
        name: "popIn・健康記事レコメンド",
        horse: "キジレコシノビ",
        odds: 8.4,
        media: "popIn",
        setup: "記事下レコメンド / 聞こえチェック記事LP",
        allocation: "ネイティブ80%・検証20%",
        stats: { fit: 56, stability: 56, burst: 66, client: 54 },
      },
      {
        name: "LINE・家族グループ内で話題化",
        horse: "カゾクグループ",
        odds: 10.8,
        media: "LINE",
        setup: "50-60代配信 / 『親に送るリスト』企画",
        allocation: "配信70%・友だち追加20%・検証10%",
        stats: { fit: 52, stability: 50, burst: 78, client: 62 },
      },
    ],
    incidents: [
      {
        type: "現場カットイン",
        title: "店舗の予約枠が水曜だけ埋まらない",
        body: "水曜訴求バナーの作成依頼が来る。広告は曜日調整装置ではないのだが。",
        effect: { stability: -8, client: 8 },
      },
      {
        type: "表現事故",
        title: "『聞こえにくい』表現の配慮不足を指摘",
        body: "当事者団体からの真っ当な指摘。クリエイティブを丁寧に作り直す。",
        effect: { burst: -10, stability: -6, client: 4 },
      },
      {
        type: "奇跡",
        title: "人気ドラマで補聴器が重要アイテムに",
        body: "検索が世代を超えて増える。家族ワードが一気に刈れる。",
        effect: { fit: 11, burst: 7 },
      },
    ],
  },
  {
    client: "チームナビ人事クラウド",
    industry: "BtoB SaaS（HR）",
    kpi: "商談化リード 月40件",
    budget: "月200万円",
    absurdity: "中",
    brief:
      "タレントマネジメントSaaS。決裁者は人事部長だが、検索するのは現場の人事担当。ホワイトペーパーは今月も増え続け、読まれた気配はあまりない。",
    plans: [
      {
        name: "Google検索・人事課題ワード",
        horse: "ジンジケンサク",
        odds: 2.4,
        media: "Google",
        setup: "評価制度/タレマネワード / 資料請求CV",
        allocation: "検索75%・指名15%・検証10%",
        stats: { fit: 87, stability: 82, burst: 44, client: 66 },
      },
      {
        name: "LinkedIn・人事責任者ターゲ",
        horse: "ケッサイシャネライ",
        odds: 5.4,
        media: "LinkedIn",
        setup: "人事部長職 / 導入事例WP / ABM風",
        allocation: "役職配信80%・検証20%",
        stats: { fit: 74, stability: 64, burst: 48, client: 80 },
      },
      {
        name: "Meta・人事あるある動画",
        horse: "ジンジアルアル",
        odds: 6.8,
        media: "Facebook/Instagram",
        setup: "評価シーズンあるある / 共感から認知",
        allocation: "動画60%・静止画25%・リタゲ15%",
        stats: { fit: 60, stability: 54, burst: 78, client: 52 },
      },
      {
        name: "UNIVERSE・ビジネス面DSP",
        horse: "ビジネスメンメン",
        odds: 12.5,
        media: "UNIVERSE",
        setup: "ビジネスアプリ面 / WP誘導 / CPC抑制",
        allocation: "アプリ面80%・検証20%",
        stats: { fit: 50, stability: 52, burst: 70, client: 54 },
      },
    ],
    incidents: [
      {
        type: "営業カットイン",
        title: "『このリード、情報収集目的では』",
        body: "インサイドセールスからの鋭い指摘。MQLの定義会議、今期3回目。",
        effect: { fit: -9, client: -10, stability: 5 },
      },
      {
        type: "競合動向",
        title: "競合が比較広告を突っ込んでくる",
        body: "自社名+比較ワードのCPCが3倍に。指名防衛費が膨らむ。",
        effect: { stability: -10, fit: -5 },
      },
      {
        type: "奇跡",
        title: "人的資本開示の義務化が話題に",
        body: "タレマネ市場全体が追い風。課題ワードの検索が底上げされる。",
        effect: { fit: 10, client: 6 },
      },
    ],
  },
  {
    client: "みまもりコネクト",
    industry: "見守りアプリ・IoT",
    kpi: "アプリDL 月20,000件 + 有料プラン転換",
    budget: "月170万円",
    absurdity: "中",
    brief:
      "子どもと高齢の親、両方を見守れるアプリ。『家族の安心』という感情商材だが、計測はインストール単価でシビアに刻まれる。感情と単価の板挟み。",
    plans: [
      {
        name: "LINE・保護者層配信",
        horse: "ホゴシャチョクゲキ",
        odds: 3.2,
        media: "LINE",
        setup: "子育て層 / 新学期タイミング / DL直結",
        allocation: "配信70%・友だち追加20%・検証10%",
        stats: { fit: 78, stability: 70, burst: 62, client: 60 },
      },
      {
        name: "Moloco・アプリDSPで機械学習全振り",
        horse: "キカイガクシュウ",
        odds: 4.6,
        media: "Moloco",
        setup: "アプリ面DSP / ML入札 / イベント最適化",
        allocation: "DSP85%・クリエイティブ検証15%",
        stats: { fit: 72, stability: 64, burst: 68, client: 46 },
      },
      {
        name: "Meta・見守りエピソード動画",
        horse: "アンシンエピソード",
        odds: 5.6,
        media: "Facebook/Instagram",
        setup: "実話風エピソード / 共感訴求 / DL誘導",
        allocation: "動画65%・静止画20%・リタゲ15%",
        stats: { fit: 66, stability: 58, burst: 74, client: 66 },
      },
      {
        name: "SmartNews・防犯ニュース面",
        horse: "ボウハンニュース",
        odds: 9.5,
        media: "SmartNews",
        setup: "地域防犯ニュース隣接 / 記事風",
        allocation: "記事面75%・検証25%",
        stats: { fit: 54, stability: 56, burst: 64, client: 58 },
      },
    ],
    incidents: [
      {
        type: "ストア事故",
        title: "OSアップデートで位置情報の仕様変更",
        body: "アプリの目玉機能が一時的に不安定に。レビュー欄がにぎやかになる。",
        effect: { stability: -13, fit: -6 },
      },
      {
        type: "クライアント横やり",
        title: "『不安を煽る訴求はNGで』",
        body: "防犯商材から不安を抜くと何が残るのか。安心が残った。CVRは減った。",
        effect: { client: 13, burst: -10 },
      },
      {
        type: "奇跡",
        title: "自治体が見守りアプリ導入を推奨",
        body: "ニュースで市場全体が追い風。DL単価が静かに下がる。",
        effect: { fit: 9, stability: 8 },
      },
    ],
  },
];

// どの案件でも起こりうる汎用ハプニング。毎レースここから抽選で混ざるため展開が毎回変わる。
const GENERIC_INCIDENTS = [
  {
    type: "計測事故",
    title: "GTMのタグが誰かの『検証』で止まっていた",
    body: "コンバージョンが3時間分消失。学習がリセット気味に。",
    effect: { fit: -6, stability: -9 },
  },
  {
    type: "媒体アップデート",
    title: "入札アルゴリズムがサイレント変更",
    body: "リリースノートには何も書いていない。挙動だけが変わる。",
    effect: { stability: -10, burst: 7 },
  },
  {
    type: "奇跡",
    title: "競合が予算を使い切って撤退",
    body: "オークションが突然ぬるくなる。CPCが静かに下がる。",
    effect: { fit: 7, burst: 8 },
  },
  {
    type: "クライアント横やり",
    title: "『バナーは全部赤にして』",
    body: "赤くなった。CTRは上がったのか下がったのか誰にも分からない。",
    effect: { client: 13, fit: -6 },
  },
  {
    type: "予算事故",
    title: "請求上限に到達して配信が夕方に停止",
    body: "カードの上限申請は明日以降。ゴールデンタイムが沈黙する。",
    effect: { burst: -12, stability: -5 },
  },
  {
    type: "代理店あるある",
    title: "レポート提出日とレース日が重なる",
    body: "運用者の集中力が資料作成に吸われる。微調整が止まる。",
    effect: { stability: -6, client: 6 },
  },
  {
    type: "奇跡",
    title: "インフルエンサーが勝手に紹介してくれた",
    body: "誰も依頼していない。指名検索とSNS流入が同時に伸びる。",
    effect: { burst: 12, client: 6 },
  },
];
